version: '3.6'
services:
  portainer:
    container_name: 'portainer'
    image: 'portainer/portainer'
    network_mode: 'bridge'
    ports:
      - '8000:8000/tcp'
      - '9000:9000/tcp'
    restart: 'unless-stopped'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/volume1/docker/portainer/data:/data'
