version: "3.6"
services:
  alertmanager:
    container_name: "alertmanager"
    image: "prom/alertmanager:latest"
    ports:
      - "9093:9093/tcp"
    restart: unless-stopped
    volumes:
      - "/volume1/docker/alertmanager/data:/alertmanager"
      - "/volume1/docker/alertmanager/config:/etc/alertmanager"
  container-exporter:
    image: "prom/container-exporter"
    ports:
      - "9104:9104/tcp"
    volumes:
      - "/sys/fs/cgroup:/cgroup"
      - "/var/run/docker.sock:/var/run/docker.sock"
  grafana:
    container_name: "grafana"
    environment:
      - "GF_USERS_ALLOW_SIGN_UP=false"
      - "GF_SECURITY_ADMIN_PASSWORD=sbr1663"
      - "GF_SECURITY_ADMIN_USER=admin"
    image: "grafana/grafana:latest"
    ports:
      - "3000:3000/tcp"
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - "/volume1/docker/grafana/datasources:/etc/grafana/provisioning/datasources"
      - "/volume1/docker/grafana/data:/var/lib/grafana"
      - "/volume1/docker/grafana/dashboards:/etc/grafana/provisioning/dashboards"
  loki:
    container_name: loki
    command:
      - "-config.file=/etc/loki/config.yaml"
    image: "grafana/loki:latest"
    ports:
      - "3100:3100/tcp"
    volumes:
      - "/volume1/docker/loki/wal:/wal"
      - "/volume1/docker/loki/config:/etc/loki:ro"
      - "/volume1/docker/loki/data:/loki/chunks"
  node-exporter:
    container_name: "node-exporter"
    hostname: "nas"
    image: "prom/node-exporter:latest"
    ports:
      - "9100:9100/tcp"
    restart: unless-stopped
    volumes:
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/:/rootfs:ro"
  process-exporter:
    container_name: "process-exporter"
    command:
      - "--procfs"
      - "/host/proc"
      - "-config.path"
      - "/config/config.yaml"
    image: "ncabatoff/process-exporter:latest"
    ports:
      - "9256:9256/tcp"
    volumes:
      - "/volume1/docker/process-exporter/config:/config"
      - "/proc:/host/proc"
  prometheus:
    container_name: "prometheus"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    expose:
      - "9090/tcp"
    image: "prom/prometheus:latest"
    volumes:
      - "/volume1/docker/prometheus/config:/etc/prometheus"
      - "/volume1/docker/prometheus/data:/prometheus"
  promtail:
    container_name: "promtail"
    command:
      - "-config.file=/etc/promtail/config.yaml"
    image: "grafana/promtail"
    volumes:
      - "/volume1/docker/promtail/config:/etc/promtail"
      - "/var/log:/var/log"
      - "/volume1/logs/synoscheduler:/volume1/logs/synoscheduler"
  snmp-exporter:
    container_name: "snmp-exporter"
    command:
      - "--config.file=/etc/snmp_exporter/snmp.yml"
    image: "prom/snmp-exporter:latest"
    ports:
      - "116:116/udp"
      - "9116:9116/tcp"
    volumes:
      - "/volume1/docker/snmp-exporter/config:/etc/snmp_exporter"
