version: '3.6'
services:
  alertmanager:
    container_name: 'alertmanager'
    image: 'prom/alertmanager:latest'
    ports:
      - '9093:9093/tcp'
    volumes:
      - '/volume1/docker/alertmanager/data:/alertmanager'
      - '/volume1/docker/alertmanager/config:/etc/alertmanager'
    restart: unless-stopped
  container-exporter:
    container_name: 'container-exporter'
    image: 'prom/container-exporter'
    ports:
      - '9104:9104/tcp'
    volumes:
      - '/sys/fs/cgroup:/cgroup'
      - '/var/run/docker.sock:/var/run/docker.sock'
    restart: unless-stopped
  grafana:
    container_name: 'grafana'
    image: 'grafana/grafana:latest'
    environment:
      - 'GF_USERS_ALLOW_SIGN_UP=false'
      - 'GF_SECURITY_ADMIN_PASSWORD=sbr1663'
      - 'GF_SECURITY_ADMIN_USER=admin'
    ports:
      - '3000:3000/tcp'
    network_mode: 'host'
    volumes:
      - '/volume1/docker/grafana/datasources:/etc/grafana/provisioning/datasources'
      - '/volume1/docker/grafana/data:/var/lib/grafana'
      - '/volume1/docker/grafana/dashboards:/etc/grafana/provisioning/dashboards'
    restart: unless-stopped
  loki:
    container_name: loki
    image: 'grafana/loki:latest'
    command:
      - '-config.file=/etc/loki/config.yaml'
    ports:
      - '3100:3100/tcp'
    volumes:
      - '/volume1/docker/loki/wal:/wal'
      - '/volume1/docker/loki/config:/etc/loki:ro'
      - '/volume1/docker/loki/data:/loki/chunks'
    restart: unless-stopped
  node-exporter:
    container_name: 'node-exporter'
    image: 'prom/node-exporter:latest'
    hostname: 'nas'
    ports:
      - '9100:9100/tcp'
    volumes:
      - '/proc:/host/proc:ro'
      - '/sys:/host/sys:ro'
      - '/:/rootfs:ro'
    restart: unless-stopped
  process-exporter:
    container_name: 'process-exporter'
    image: 'ncabatoff/process-exporter:latest'
    command:
      - '--procfs'
      - '/host/proc'
      - '-config.path'
      - '/config/config.yaml'
    ports:
      - '9256:9256/tcp'
    volumes:
      - '/volume1/docker/process-exporter/config:/config'
      - '/proc:/host/proc'
    restart: unless-stopped
  prometheus:
    container_name: 'prometheus'
    image: 'prom/prometheus:latest'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - '9090:9090/tcp'
    volumes:
      - '/volume1/docker/prometheus/config:/etc/prometheus'
      - '/volume1/docker/prometheus/data:/prometheus'
    restart: unless-stopped
  promtail:
    container_name: 'promtail'
    image: 'grafana/promtail'
    command:
      - '-config.file=/etc/promtail/config.yaml'
    volumes:
      - '/volume1/docker/promtail/config:/etc/promtail'
      - '/var/log:/var/log'
      - '/volume1/logs/synoscheduler:/volume1/logs/synoscheduler'
    restart: unless-stopped
  snmp-exporter:
    container_name: 'snmp-exporter'
    image: 'prom/snmp-exporter:latest'
    command:
      - '--config.file=/etc/snmp_exporter/snmp.yml'
    ports:
      - '116:116/udp'
      - '9116:9116/tcp'
    volumes:
      - '/volume1/docker/snmp-exporter/config:/etc/snmp_exporter'
    restart: unless-stopped
