version: "3.6"
services:
  docker-autocompose:
    command:
      - "sleep"
      - "infinity"
    image: "ghcr.io/red5d/docker-autocompose:latest"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  ubuntu:
    command:
      - "tail"
      - "-f"
      - "/dev/null"
    image: "ubuntu:latest"
    volumes:
      - "/volume1/data:/ds/data"
      - "/volume1/homes:/ds/homes"
      - "/volume1/docker/ubuntu/root:/root"
      - "/volume1/logs:/ds/logs"
      - "/volume1/paperless:/ds/paperless"
    working_dir: "/ds"
  watchtower:
    command:
      - "--run-once"
    environment:
      - "TZ=Europe/Zurich"
      - "WATCHTOWER_CLEANUP=true"
      - "WATCHTOWER_INCLUDE_STOPPED=true"
    expose:
      - "8080/tcp"
    image: "containrrr/watchtower"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
