version: "3.6"
services:
  postgres:
    container_name: postgres
    command:
      - "postgres"
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "work_mem=16MB"
    environment:
      - "POSTGRES_DB=paperless"
      - "POSTGRES_USER=paperless"
      - "POSTGRES_PASSWORD=1234"
    image: "postgres:12"
    ports:
      - ":5432/tcp"
    restart: unless-stopped
    volumes:
      - "/volume1/Backup/Paperless/pgdata:/var/lib/postgresql/data"
