services:
  graphite:
    container_name: ${CONTAINER_PREFIX}graphite
    image: sitespeedio/graphite:1.1.10-3
    ports:
      - ${GRAPHITE_PORT}:2003/tcp
      - ${GRAPHITE_HTTP_PORT}:80/tcp
    volumes:
      - ${CONFIGURATION_FOLDER}/graphite/data:/opt/graphite/storage
      - ${CONFIGURATION_FOLDER}/graphite/custom_functions:/opt/graphite/webapp/graphite/functions/custom
      - ${CONFIGURATION_FOLDER}/graphite/statd:/opt/statsd/config
      - ${CONFIGURATION_FOLDER}/graphite/log:/var/log
      - ${CONFIGURATION_FOLDER}/graphite/config:/opt/graphite/conf
    restart: unless-stopped
  # netatmo-exporter:
  #   container_name: ${CONTAINER_PREFIX}netatmo-exporter
  #   environment:
  #     - NETATMO_EXPORTER_ADDR=${CONTAINER_PREFIX}netatmo-exporter:9210
  #     - NETATMO_CLIENT_PASSWORD
  #     - NETATMO_CLIENT_USERNAME
  #     - NETATMO_CLIENT_SECRET
  #     - NETATMO_CLIENT_ID
  #   image: xperimental/netatmo-exporter:latest
  #   ports:
  #     - ${NETATMO_EXPORTER_PORT}:9210/tcp
  #   restart: unless-stopped
  netatmo2graphite:
    container_name: ${CONTAINER_PREFIX}netatmo2graphite
    environment:
      - LOGLEVEL
      - GRAPHITE_HOST=${CONTAINER_PREFIX}graphite
      - NETATMO_CLIENT_PASSWORD
      - NETATMO_CLIENT_USERNAME
      - NETATMO_CLIENT_SECRET
      - NETATMO_CLIENT_ID
      - CLIENT_ID
      - CLIENT_SECRET
      - REFRESH_TOKEN
      - DAEMON_DELAY_SECONDS
      - DAEMON_DEFAULT_TIMESTAMP
      - DAEMON_PROCESS_ADD_ON_IGNORE_SECOUNDS
      - DAEMON_PROCESS_MAX_MISSING_SECOUNDS
    image: sbrunner/netatmo2graphite:latest
    volumes:
      - ${CONFIGURATION_FOLDER}/netatmo2graphite/config:/etc/netatmo2graphite
      - ${CONFIGURATION_FOLDER}/netatmo2graphite/root:/root
    restart: unless-stopped
