version: '3.6'
services:
  whats-up:
    container_name: ${CONTAINER_PREFIX}whats-up
    image: fmartinou/whats-up-docker:6.6.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - ${PORT_3000}:3000
    restart: unless-stopped
