services:
  sbrunner-scan-to-paperless:
    container_name: ${CONTAINER_PREFIX}scan-to-paperless
    image: ghcr.io/sbrunner/scan-to-paperless:${SCAN_TO_PAPERLESS_TAG}
    environment:
      - PROGRESS
      - EXPERIMENTAL
      - DEBUG_INOTIFY
    volumes:
      - ${PAPERLESS_FOLDER}/scan-codes:/scan-codes
      - ${PAPERLESS_FOLDER}/scan:/source
      - ${PAPERLESS_FOLDER}/consume:/destination
    restart: unless-stopped
