version: "3.6"
services:
  docker-autocompose:
    container_name: "docker-autocompose"
    image: "ghcr.io/red5d/docker-autocompose:latest"
    command:
      - "tail"
      - "-f"
      - "/dev/null"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped
  ubuntu:
    container_name: ubuntu
    image: "ubuntu:latest"
    command:
      - "tail"
      - "-f"
      - "/dev/null"
    environment:
      - "TZ"
      - "COMPOSE_PROJECT_NAME"
    volumes:
      - "/volume1/data:/ds/data"
      - "/volume1/homes:/ds/homes"
      - "/volume1/docker/ubuntu/root:/root"
      - "/volume1/logs:/ds/logs"
      - "/volume1/paperless:/ds/paperless"
    working_dir: "/ds"
    restart: unless-stopped
  watchtower:
    container_name: "watchtower"
    image: "containrrr/watchtower"
    command:
      - "--run-once"
    environment:
      - "TZ"
      - "WATCHTOWER_CLEANUP"
      - "WATCHTOWER_INCLUDE_STOPPED"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
