version: '3.6'
services:
  docker-autocompose:
    extends:
      file: ./docker-compose-lib.yaml
      service: docker-autocompose
  ubuntu: &ubuntu
    container_name: ${CONTAINER_PREFIX}ubuntu
    image: sbrunner/vim:latest
    command:
      - tail
      - -f
      - /dev/null
    environment:
      - COMPOSE_PROJECT_NAME
      - TZ
      - SHELL
      - CRON_TZ
      - MAILTO
      - MAILFROM
      - RANDOM_DELAY
    volumes:
      - /volume1/data:/volume1/data
      - /volume1/homes:/volume1/homes
      - ${CONFIGURATION_FOLDER}/ubuntu/root:/root
      - ${CONFIGURATION_FOLDER}/ubuntu/logs:/logs
      - /volume1/logs:/volume1/logs
      - /volume1/paperless:/volume1/paperless
      - ${CONFIGURATION_FOLDER}/ubuntu/cron.d:/etc/cron.d
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/docker:/volume1/docker
    working_dir: /volume1
    restart: unless-stopped
  cron:
    <<: *ubuntu
    container_name: ${CONTAINER_PREFIX}cron
    command:
      - cron
      - -f
  watchtower:
    extends:
      file: ./docker-compose-lib.yaml
      service: watchtower
